spring:
  application:
    name: lawyerAssistant

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lawyerAssistant}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}